### ISSUE TITLE
Error from `figwheel-sidecar`

### ISSUE THREAD

**Issue by gfrivolt** [aJchemist/boot-figwheel#3] opened 2015-12-31 17:57 UTC
I followed the steps from the README, but I got this issue:

```
→ boot dev                                                                 1 ↵
Require figwheel-sidecar.system...
             clojure.lang.ExceptionInfo: java.io.FileNotFoundException: Could n
ot locate clojure/tools/nrepl/middleware/interruptible_eval__init.class or cloj
ure/tools/nrepl/middleware/interruptible_eval.clj on classpath. Please check th
at namespaces with dashes use underscores in the Clojure file name., compiling:
(figwheel_sidecar/repl.clj:1:1)
    data: {:file
           "/var/folders/vg/ggzzlh2n6jb8_xt85lk0rcv80000gn/T/boot.user416308939
4503087091.clj",
           :line 25}
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could n
ot locate clojure/tools/nrepl/middleware/interruptible_eval__init.class or cloj
ure/tools/nrepl/middleware/interruptible_eval.clj on classpath. Please check th
at namespaces with dashes use underscores in the Clojure file name., compiling:
(figwheel_sidecar/repl.clj:1:1)
```

Thanks for any suggestion.

**Comment by ajchemist** [comment] 2016-03-28 02:52
Sorry, it's toooo late.

It seems a deps problem, but I can't reproduce this error.
Did you add `nrepl` into project deps?
Maybe your `build.boot` details will helps for resolving this issue.

**Comment by tiye** [comment] 2016-03-29 01:44
Same here and fixed by adding `nrepl` in dependency.

**Closed as completed** 2016-04-19 10:11 UTC
